### ISSUE TITLE
Dialog box is not responsive in mobile view

### ISSUE THREAD

**Issue by molayodecker** [biplabpokhrel/biplab-notifier#20]
When you display dialog notification in mobile view is does not wrap to the view port
<img width="380" alt="Screen Shot 2019-03-19 at 4 48 39 PM" src="https://user-images.githubusercontent.com/12972201/54640887-34d56d00-4a67-11e9-816a-cd81421d69b8.png">

**Comment by biplabpokhrel** [comment]
Issue fixed in version 2.0.5
